"""
Django settings for ovation_prime_site project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .base_settings import *
from pathlib import Path


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'example'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# ключ для прокси-сервера
PROXY_API_KEY = ''

YA_DISK_TOKEN = ''
YA_DISK_DIR = ''